### ISSUE TITLE
agent learned unexpected IP and panic

### ISSUE THREAD

**Issue by zwtop** [smartxworks/lynx#63]
see log:
```
time="2021-04-07T05:43:20Z" level=info msg="Flush Learned localOfPort endpointInfo 6 : 10.0.0.4." 
time="2021-04-07T05:43:20Z" level=info msg="Deleted flow: {\"Priority\":100,\"InputPort\":0,\"MacDa\":\"lhKZi2aa\",\"MacDaMask\":null,\"MacSa\":null,\"MacSaMask\":null,\"Ethertype\":2048,\"VlanId\":0,\"ArpOper\":0,\"IpSa\":null,\"IpSaMask\":null,\"IpDa\":null,\"IpDaMask\":null,\"Ipv6Sa\":null,\"Ipv6SaMask\":null,\"Ipv6Da\":null,\"Ipv6DaMask\":null,\"IpProto\":0,\"IpDscp\":0,\"TcpSrcPort\":0,\"TcpDstPort\":0,\"UdpSrcPort\":0,\"UdpDstPort\":0,\"Metadata\":null,\"MetadataMask\":null,\"TunnelId\":0,\"TcpFlags\":null,\"TcpFlagsMask\":null,\"CtStates\":null}" 
time="2021-04-07T05:43:20Z" level=info msg="local ofport 2 related endpoint ipaddress update from 10.0.0.126 to 10.0.0.88" 
time="2021-04-07T05:43:20Z" level=info msg="Learning localOfPort endpointInfo 2 : 10.0.0.88." 
time="2021-04-07T05:43:20Z" level=info msg="local ofport 10 related ovsport was't learned or ofPort update" 
time="2021-04-07T05:43:20Z" level=info msg="Flush Learned localOfPort endpointInfo 3 : 10.0.0.212." 
time="2021-04-07T05:43:20Z" level=info msg="Deleted flow: {\"Priority\":100,\"InputPort\":0,\"MacDa\":\"UlQAYtvT\",\"MacDaMask\":null,\"MacSa\":null,\"MacSaMask\":null,\"Ethertype\":2048,\"VlanId\":0,\"ArpOper\":0,\"IpSa\":null,\"IpSaMask\":null,\"IpDa\":null,\"IpDaMask\":null,\"Ipv6Sa\":null,\"Ipv6SaMask\":null,\"Ipv6Da\":null,\"Ipv6DaMask\":null,\"IpProto\":0,\"IpDscp\":0,\"TcpSrcPort\":0,\"TcpDstPort\":0,\"UdpSrcPort\":0,\"UdpDstPort\":0,\"Metadata\":null,\"MetadataMask\":null,\"TunnelId\":0,\"TcpFlags\":null,\"TcpFlagsMask\":null,\"CtStates\":null}" 
time="2021-04-07T05:43:20Z" level=info msg="local ofport 10 related ovsport was't learned or ofPort update" 
time="2021-04-07T05:43:20Z" level=info msg="local ofport 10 related ovsport was't learned or ofPort update" 
time="2021-04-07T05:43:20Z" level=info msg="local ofport 10 related ovsport was't learned or ofPort update" 
time="2021-04-07T05:43:20Z" level=info msg="local ofport 10 related ovsport was't learned or ofPort update" 
time="2021-04-07T05:43:20Z" level=info msg="local ofport 10 related ovsport was't learned or ofPort update" 
time="2021-04-07T05:43:20Z" level=info msg="local ofport 10 related ovsport was't learned or ofPort update" 
time="2021-04-07T05:43:20Z" level=info msg="local ofport 10 related ovsport was't learned or ofPort update" 
time="2021-04-07T05:43:20Z" level=info msg="local ofport 1 related endpoint ipaddress update from 10.0.0.168 to 192.168.29.62" 
time="2021-04-07T05:43:20Z" level=info msg="Learning localOfPort endpointInfo 1 : 192.168.29.62." 
time="2021-04-07T05:43:20Z" level=info msg="local ofport 10 related ovsport was't learned or ofPort update" 
time="2021-04-07T05:43:20Z" level=info msg="local ofport 10 related ovsport was't learned or ofPort update" 
time="2021-04-07T05:43:20Z" level=info msg="local ofport 10 related ovsport was't learned or ofPort update" 
time="2021-04-07T05:43:20Z" level=info msg="local ofport 10 related ovsport was't learned or ofPort update" 
time="2021-04-07T05:43:20Z" level=info msg="local ofport 10 related ovsport was't learned or ofPort update" 
time="2021-04-07T05:43:20Z" level=info msg="local ofport 10 related ovsport was't learned or ofPort update" 
time="2021-04-07T05:43:20Z" level=info msg="local ofport 10 related ovsport was't learned or ofPort update" 
time="2021-04-07T05:43:20Z" level=info msg="local ofport 10 related ovsport was't learned or ofPort update" 
time="2021-04-07T05:43:20Z" level=info msg="Flush Learned localOfPort endpointInfo 4 : 10.0.0.19." 
time="2021-04-07T05:43:20Z" level=info msg="Deleted flow: {\"Priority\":100,\"InputPort\":0,\"MacDa\":\"mjPu89Da\",\"MacDaMask\":null,\"MacSa\":null,\"MacSaMask\":null,\"Ethertype\":2048,\"VlanId\":0,\"ArpOper\":0,\"IpSa\":null,\"IpSaMask\":null,\"IpDa\":null,\"IpDaMask\":null,\"Ipv6Sa\":null,\"Ipv6SaMask\":null,\"Ipv6Da\":null,\"Ipv6DaMask\":null,\"IpProto\":0,\"IpDscp\":0,\"TcpSrcPort\":0,\"TcpDstPort\":0,\"UdpSrcPort\":0,\"UdpDstPort\":0,\"Metadata\":null,\"MetadataMask\":null,\"TunnelId\":0,\"TcpFlags\":null,\"TcpFlagsMask\":null,\"CtStates\":null}" 
time="2021-04-07T05:43:20Z" level=info msg="local ofport 10 related ovsport was't learned or ofPort update" 
time="2021-04-07T05:43:20Z" level=info msg="Flush Learned localOfPort endpointInfo 5 : 10.0.0.72." 
time="2021-04-07T05:43:20Z" level=info msg="Deleted flow: {\"Priority\":100,\"InputPort\":0,\"MacDa\":\"Bl1yhYCg\",\"MacDaMask\":null,\"MacSa\":null,\"MacSaMask\":null,\"Ethertype\":2048,\"VlanId\":0,\"ArpOper\":0,\"IpSa\":null,\"IpSaMask\":null,\"IpDa\":null,\"IpDaMask\":null,\"Ipv6Sa\":null,\"Ipv6SaMask\":null,\"Ipv6Da\":null,\"Ipv6DaMask\":null,\"IpProto\":0,\"IpDscp\":0,\"TcpSrcPort\":0,\"TcpDstPort\":0,\"UdpSrcPort\":0,\"UdpDstPort\":0,\"Metadata\":null,\"MetadataMask\":null,\"TunnelId\":0,\"TcpFlags\":null,\"TcpFlagsMask\":null,\"CtStates\":null}" 
time="2021-04-07T05:43:20Z" level=info msg="local ofport 10 related ovsport was't learned or ofPort update" 
time="2021-04-07T05:43:20Z" level=info msg="Flush Learned localOfPort endpointInfo 2 : 10.0.0.88." 
time="2021-04-07T05:43:20Z" level=info msg="Deleted flow: {\"Priority\":100,\"InputPort\":0,\"MacDa\":\"phdoe3wB\",\"MacDaMask\":null,\"MacSa\":null,\"MacSaMask\":null,\"Ethertype\":2048,\"VlanId\":0,\"ArpOper\":0,\"IpSa\":null,\"IpSaMask\":null,\"IpDa\":null,\"IpDaMask\":null,\"Ipv6Sa\":null,\"Ipv6SaMask\":null,\"Ipv6Da\":null,\"Ipv6DaMask\":null,\"IpProto\":0,\"IpDscp\":0,\"TcpSrcPort\":0,\"TcpDstPort\":0,\"UdpSrcPort\":0,\"UdpDstPort\":0,\"Metadata\":null,\"MetadataMask\":null,\"TunnelId\":0,\"TcpFlags\":null,\"TcpFlagsMask\":null,\"CtStates\":null}" 
time="2021-04-07T05:43:20Z" level=info msg="local ofport 10 related ovsport was't learned or ofPort update" 
time="2021-04-07T05:43:20Z" level=info msg="local ofport 10 related ovsport was't learned or ofPort update" 
time="2021-04-07T05:43:20Z" level=info msg="local ofport 10 related ovsport was't learned or ofPort update" 
time="2021-04-07T05:43:20Z" level=info msg="local ofport 1 related endpoint ipaddress update from 192.168.29.62 to 192.168.24.66" 
time="2021-04-07T05:43:20Z" level=info msg="Learning localOfPort endpointInfo 1 : 192.168.24.66." 
time="2021-04-07T05:43:20Z" level=info msg="local ofport 10 related ovsport was't learned or ofPort update" 
time="2021-04-07T05:43:20Z" level=info msg="local ofport 10 related ovsport was't learned or ofPort update" 
time="2021-04-07T05:43:20Z" level=info msg="local ofport 10 related ovsport was't learned or ofPort update" 
time="2021-04-07T05:43:20Z" level=info msg="local ofport 1 related endpoint ipaddress update from 192.168.24.66 to 10.0.0.168" 
time="2021-04-07T05:43:20Z" level=info msg="Learning localOfPort endpointInfo 1 : 10.0.0.168." 
time="2021-04-07T05:43:20Z" level=error msg="Flow {\"Priority\":100,\"InputPort\":0,\"MacDa\":\"mprLiPAf\",\"MacDaMask\":null,\"MacSa\":null,\"MacSaMask\":null,\"Ethertype\":2048,\"VlanId\":0,\"ArpOper\":0,\"IpSa\":null,\"IpSaMask\":null,\"IpDa\":null,\"IpDaMask\":null,\"Ipv6Sa\":null,\"Ipv6SaMask\":null,\"Ipv6Da\":null,\"Ipv6DaMask\":null,\"IpProto\":0,\"IpDscp\":0,\"TcpSrcPort\":0,\"TcpDstPort\":0,\"UdpSrcPort\":0,\"UdpDstPort\":0,\"Metadata\":null,\"MetadataMask\":null,\"TunnelId\":0,\"TcpFlags\":null,\"TcpFlagsMask\":null,\"CtStates\":null} already exists" 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5c041b]

goroutine 211 [running]:
github.com/contiv/ofnet/ofctrl.(*Flow).Next(0x0, 0x1cab638, 0xc0006b6820, 0x0, 0x0)
	/opt/golang/pkg/mod/github.com/smartxworks/ofnet@v0.0.0-20210401021035-3906e94e9cae/ofctrl/fgraphFlow.go:551 +0x3b
github.com/contiv/ofnet.(*VlanArpLearnerBridge).installIngressSelectFlow(0xc0000ffb00, 0xc00066b040, 0x6, 0x7c0, 0x2, 0xc00066b046)
	/opt/golang/pkg/mod/github.com/smartxworks/ofnet@v0.0.0-20210401021035-3906e94e9cae/vlanArpLearnBridge.go:426 +0x1ca
github.com/contiv/ofnet.(*VlanArpLearnerBridge).learnFromArp(0xc0000ffb00, 0x1040608000001, 0xc00066b040, 0x6, 0x7c0, 0xc00066b046, 0x4, 0x7ba, 0xc00066b04a, 0x6, ...)
	/opt/golang/pkg/mod/github.com/smartxworks/ofnet@v0.0.0-20210401021035-3906e94e9cae/vlanArpLearnBridge.go:313 +0xefc
github.com/contiv/ofnet.(*VlanArpLearnerBridge).processArp(0xc0000ffb00, 0x0, 0xc0007f8494, 0x6, 0x6, 0xc0007f849a, 0x6, 0x6, 0x806000000000000, 0x1cca240, ...)
	/opt/golang/pkg/mod/github.com/smartxworks/ofnet@v0.0.0-20210401021035-3906e94e9cae/vlanArpLearnBridge.go:297 +0x225
github.com/contiv/ofnet.(*VlanArpLearnerBridge).PacketRcvd(0xc0000ffb00, 0xc0005bea20, 0xc0007fb4a0)
	/opt/golang/pkg/mod/github.com/smartxworks/ofnet@v0.0.0-20210401021035-3906e94e9cae/vlanArpLearnBridge.go:263 +0x105
github.com/contiv/ofnet.(*OfnetAgent).PacketRcvd(0xc0002c6fc0, 0xc0005bea20, 0xc0007fb4a0)
	/opt/golang/pkg/mod/github.com/smartxworks/ofnet@v0.0.0-20210401021035-3906e94e9cae/ofnetAgent.go:466 +0xe7
github.com/contiv/ofnet/ofctrl.(*OFSwitch).handleMessages(0xc0005bea20, 0xc0006457b0, 0x8, 0x8, 0x1cc9df0, 0xc0007fb4a0)
	/opt/golang/pkg/mod/github.com/smartxworks/ofnet@v0.0.0-20210401021035-3906e94e9cae/ofctrl/ofSwitch.go:203 +0x633
github.com/contiv/ofnet/ofctrl.(*OFSwitch).receive(0xc0005bea20)
	/opt/golang/pkg/mod/github.com/smartxworks/ofnet@v0.0.0-20210401021035-3906e94e9cae/ofctrl/ofSwitch.go:135 +0x71
created by github.com/contiv/ofnet/ofctrl.NewSwitch
	/opt/golang/pkg/mod/github.com/smartxworks/ofnet@v0.0.0-20210401021035-3906e94e9cae/ofctrl/ofSwitch.go:69 +0x3b6

```

Please note that：
```
"local ofport 1 related endpoint ipaddress update from 10.0.0.168 to 192.168.29.62" 
"Learning localOfPort endpointInfo 1 : 192.168.29.62." 
"local ofport 1 related endpoint ipaddress update from 192.168.29.62 to 192.168.24.66"
"Learning localOfPort endpointInfo 1 : 192.168.24.66." 
"local ofport 1 related endpoint ipaddress update from 192.168.24.66 to 10.0.0.168" 
"Learning localOfPort endpointInfo 1 : 10.0.0.168." 
```
Unexpected IP 192.168.29.62 and 192.168.29.66 found.

**Comment by zwtop** [comment]
```
root@lynx02:~# cat /var/log/lynx-agent.log | grep Learning
time="2021-04-12T08:44:54Z" level=info msg="Learning localOfPort endpointInfo 1 : 10.0.0.108 : 96:9c:8d:c6:81:dc"
time="2021-04-12T08:45:12Z" level=info msg="Learning localOfPort endpointInfo 2 : 10.0.0.78 : 56:0b:95:f5:e7:6a"
time="2021-04-12T08:47:33Z" level=info msg="Learning localOfPort endpointInfo 2 : 10.0.0.16 : 86:90:00:72:83:7d"
time="2021-04-12T08:47:34Z" level=info msg="Learning localOfPort endpointInfo 2 : 192.168.31.84 : 9a:01:28:44:b4:17"
time="2021-04-12T08:47:35Z" level=info msg="Learning localOfPort endpointInfo 1 : 192.168.31.251 : 00:50:56:9f:2d:14"
time="2021-04-12T08:47:35Z" level=info msg="Learning localOfPort endpointInfo 1 : 10.0.0.101 : 26:44:32:2c:3e:cb"
time="2021-04-12T08:47:36Z" level=info msg="Learning localOfPort endpointInfo 1 : 192.168.30.22 : 52:54:00:62:db:d3"
time="2021-04-12T08:47:38Z" level=info msg="Learning localOfPort endpointInfo 2 : 10.0.0.67 : e6:79:80:f5:12:dd"
time="2021-04-12T08:47:40Z" level=info msg="Learning localOfPort endpointInfo 1 : 192.168.31.251 : 00:50:56:9f:2d:14"
```

**Comment by zwtop** [comment]
@kylezh @echkenluo

**Comment by echkenluo** [comment]
https://github.com/echkenluo/ofnet/commit/d997fc65768b614e795405efef4e3ad7c4d71ba9  先使用这个 branch。
